- id: '1608410519916'
  alias: Motion Indgang CCTV
  description: Tænd lyset i indgangen ved bevægelse opfanget af kameraet
  trigger:
  - platform: webhook
    webhook_id: d718eb3cc3fa4b089aa71c37fbbb4373
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.indgang
  mode: restart
- id: '1608411733721'
  alias: Birthday Update
  description: Opdater nedtællingen til kommende fødselsdage én gang i døgnet
  trigger:
  - platform: time
    at: 00:01:00
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    entity_id: sensor.next_birthday
  mode: single
- id: '1608991948003'
  alias: Tag Test Sandbox is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 2e3cbe3e-7026-4e27-ae9c-f00e50c20135
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.sandbox
  mode: single
- id: '1608992157017'
  alias: Tag Test Sandbox is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 4d9eed58-54c3-4558-9b98-c89b7dd57095
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.sandbox
  mode: single
- id: '1609275894067'
  alias: AP down - power cycle
  description: Hjaltes AP er gået død - genstart det med en powercycle
  trigger:
  - platform: state
    entity_id: binary_sensor.ap_hjalte
    from: 'on'
    for: 00:02:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.hjaltes_ap
  - delay: '5'
  - service: switch.turn_on
    data: {}
    entity_id: switch.hjaltes_ap
  - wait_template: '{{ is_state("binary_sensor.ap_hjalte", "on") }}'
    timeout: 00:05:00
    continue_on_timeout: true
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not wait.completed }}'
      sequence:
      - service: notify.mobile_app_jacobs_moto
        data:
          title: AP nede
          message: 'Hjaltes AP er nede

            '
          data:
            channel: Network
            importance: high
    default: []
  mode: single
- id: '1609276615971'
  alias: Boot
  description: Indlæs diverse lister m.m. ved opstart
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: shell_command.var_set_values
    data: {}
  - service: shell_command.select_set_options
    data: {}
  - service: shell_command.text_set_values
    data: {}
  - service: rest_command.set_options_fix
    data:
      payload: "{\"entity_id\":\"input_select.chromecasts\",\"options\":[ {%- for\
        \ chromecast in state_attr('group.chromecasts','entity_id') -%}\n  \"{{ state_attr(chromecast,\
        \ 'friendly_name') }}\"\n  {{- ',' if not loop.last -}}\n{% endfor %}]}"
  - service: rest_command.set_options_fix
    data:
      payload: "{\"entity_id\":\"input_select.chromecasts_entities\",\"options\":[\
        \ {%- for chromecast in state_attr('group.chromecasts','entity_id') -%}\n\
        \  \"{{ chromecast }}\"\n  {{- ',' if not loop.last -}}\n{% endfor %}]}"
  mode: single
- id: '1609532873074'
  alias: Pengekassen
  description: Pengekassen er blevet åbnet
  trigger:
  - platform: state
    entity_id: binary_sensor.pengekasse
    from: 'off'
  condition: []
  action:
  - service: notify.mobile_app_jacobs_moto
    data:
      title: OBS
      message: Pengekassen er blevet åbnet
      data:
        channel: Pengekasse
        importance: high
  mode: single
- id: '1609700478466'
  alias: Næste slide
  description: Skift til næste slide
  trigger:
  - platform: time_pattern
    seconds: /15
  condition:
  - condition: template
    value_template: '{{ state_attr("input_select.cards_to_slide", "options") | length
      > 1 }}'
  action:
  - service: input_select.select_next
    data: {}
    entity_id: input_select.cards_to_slide
  mode: single
- id: '1609704967146'
  alias: Greentel - Scrape Done
  description: Greentel scrape er færdig - har modtaget webhook
  trigger:
  - platform: webhook
    webhook_id: fdad0b0c5b8448579dc9255e152bc45b
  condition: []
  action:
  - service: shell_command.greentel_get
    data: {}
  mode: single
- id: '1609705058743'
  alias: Greentel Scrape Begin
  description: Start en scraping af Greentel
  trigger:
  - platform: time_pattern
    minutes: /42
  condition: []
  action:
  - service: shell_command.greentel_scrape
    data: {}
  mode: single
- id: '1610390673938'
  alias: deCONZ - All-In-One IKEA five button remote for lights
  description: ''
  use_blueprint:
    path: J-Lindvig/all_in_remote.yaml
    input:
      remote: c08819d98af8b341299ea47c702e9a37
      light:
        entity_id: light.sandbox
      group:
        entity_id: input_select.all_in_one_livingroom
- id: '1610392205581'
  alias: deCONZ - All-In-One IKEA five button remote for lights
  description: Test 1
  use_blueprint:
    path: J-Lindvig/all_in_remote.yaml
    input:
      remote: c08819d98af8b341299ea47c702e9a37
      light:
        entity_id:
        - light.sandbox
        - light.bloklys_kokken
        - light.bloklys_gangen
      group:
        entity_id: input_select.all_in_one_livingroom
- id: '1610396131009'
  alias: AAAAAAAA
  description: ''
  use_blueprint:
    path: J-Lindvig/all_in_remote.yaml
    input:
      long_press_transition: '30'
      remote: c08819d98af8b341299ea47c702e9a37
      light: group.all_in_one_group
      group: input_select.all_in_one_test
      short_press_transition: '0.5'
      dim_step_pct: '20'
