- id: '1608410519916'
  alias: Motion Indgang CCTV
  description: Tænd lyset i indgangen ved bevægelse opfanget af kameraet
  trigger:
  - platform: webhook
    webhook_id: d718eb3cc3fa4b089aa71c37fbbb4373
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.indgang
  mode: restart
- id: '1608411733721'
  alias: Birthday Update
  description: Opdater nedtællingen til kommende fødselsdage én gang i døgnet
  trigger:
  - platform: time
    at: 00:01:00
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    entity_id: sensor.next_birthday
  mode: single
- id: '1609275894067'
  alias: AP down - power cycle
  description: Hjaltes AP er gået død - genstart det med en powercycle
  trigger:
  - platform: state
    entity_id: binary_sensor.ap_hjalte
    from: 'on'
    for: 00:02:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.hjaltes_ap
  - delay: '5'
  - service: switch.turn_on
    data: {}
    entity_id: switch.hjaltes_ap
  - wait_template: '{{ is_state("binary_sensor.ap_hjalte", "on") }}'
    timeout: 00:05:00
    continue_on_timeout: true
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ not wait.completed }}'
      sequence:
      - service: notify.mobile_app_jacobs_moto
        data:
          title: AP nede
          message: 'Hjaltes AP er nede

            '
          data:
            channel: Network
            importance: high
    default: []
  mode: single
- id: '1609276615971'
  alias: Boot
  description: Indlæs diverse lister m.m. ved opstart
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: shell_command.var_set_values
    data: {}
  - service: shell_command.select_set_options
    data: {}
  - service: shell_command.text_set_values
    data: {}
  - service: rest_command.set_options_fix
    data:
      payload: "{\"entity_id\":\"input_select.chromecasts\",\"options\":[ {%- for\
        \ chromecast in state_attr('group.chromecasts','entity_id') -%}\n  \"{{ state_attr(chromecast,\
        \ 'friendly_name') }}\"\n  {{- ',' if not loop.last -}}\n{% endfor %}]}"
  - service: rest_command.set_options_fix
    data:
      payload: "{\"entity_id\":\"input_select.chromecasts_entities\",\"options\":[\
        \ {%- for chromecast in state_attr('group.chromecasts','entity_id') -%}\n\
        \  \"{{ chromecast }}\"\n  {{- ',' if not loop.last -}}\n{% endfor %}]}"
  mode: single
- id: '1609532873074'
  alias: Pengekassen
  description: Pengekassen er blevet åbnet
  trigger:
  - platform: state
    entity_id: binary_sensor.pengekasse
    from: 'off'
  condition: []
  action:
  - service: notify.mobile_app_jacobs_moto
    data:
      title: OBS
      message: Pengekassen er blevet åbnet
      data:
        channel: Pengekasse
        importance: high
  mode: single
- id: '1611953530386'
  alias: Touchpanel - Default View
  description: ''
  use_blueprint:
    path: J-Lindvig/default_view.yaml
    input:
      device: sensor.touchpanel
- id: '1614109785363'
  alias: Frederik - tutorial
  description: ''
  use_blueprint:
    path: J-Lindvig/frederik.yaml
    input:
      delay_max: '300'
      sensor: binary_sensor.kontor
      switch:
        entity_id: switch.julelys_bag
      time_before: 09:25:00
      delay_min: '60'
      time_duration: 00:00:10
      time_after: 07:00:00
