- id: '1608411733721'
  alias: Birthday Update
  description: Opdater nedtællingen til kommende fødselsdage én gang i døgnet
  trigger:
  - platform: time
    at: 00:01:00
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    entity_id: sensor.next_birthday
  mode: single
- id: '1609276615971'
  alias: Boot
  description: Indlæs diverse lister m.m. ved opstart
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: shell_command.var_set_values
    data: {}
  - service: shell_command.select_set_options
    data: {}
  - service: shell_command.text_set_values
    data: {}
  - service: rest_command.set_options_fix
    data:
      payload: "{\"entity_id\":\"input_select.chromecasts\",\"options\":[ {%- for\
        \ chromecast in state_attr('group.chromecasts','entity_id') -%}\n  \"{{ state_attr(chromecast,\
        \ 'friendly_name') }}\"\n  {{- ',' if not loop.last -}}\n{% endfor %}]}"
  - service: rest_command.set_options_fix
    data:
      payload: "{\"entity_id\":\"input_select.chromecasts_entities\",\"options\":[\
        \ {%- for chromecast in state_attr('group.chromecasts','entity_id') -%}\n\
        \  \"{{ chromecast }}\"\n  {{- ',' if not loop.last -}}\n{% endfor %}]}"
  mode: single
- id: '1611953530386'
  alias: Touchpanel - Default View
  description: ''
  use_blueprint:
    path: J-Lindvig/default_view.yaml
    input:
      device: sensor.touchpanel
- id: '1637511922649'
  alias: Hoveddør
  description: ''
  trigger:
  - platform: device
    device_id: 3ec11e64d8472fa46fd657f596fee5bc
    domain: nest
    type: camera_person
  condition: []
  action:
  - service: browser_mod.popup
    data:
      title: Hoveddør
      card:
        type: picture-entity
        entity: camera.hoveddor
        camera_view: live
      deviceID:
      - this
  mode: single
